application:
  local:
    ip: **本机IP
    port: 9862
  genesis_nodes:
    - ip: router.bittorrent.com
      port: 6881
    - ip: router.utorrent.com
      port: 6881
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://**:3306/dht?characterEncoding=utf-8&autoReconnectForPools=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: **
mybatis:
  type-aliases-package: vip.rory.dht.dao.entity
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: vip.rory.dht.dao.util.MyMapper
  not-empty: false
  identity: MYSQL